stages:
  - scanning
  - test
  - deploy

gitguardian scan:
  image: gitguardian/ggshield:latest
  stage: scanning
  script: ggshield scan ci
  tags:
    - dind

include:
  - template: Code-Quality.gitlab-ci.yml

test:php7.1:
  stage: test
  image: phpdocker/phpdocker:7.1
  tags:
    - dind
  before_script:
    - pecl install xdebug && docker-php-ext-enable xdebug
    - composer update --no-interaction
    - composer require --dev phpstan/phpstan
  script:
    #- phpcs --standard=PSR2 -nsp src tests
    - XDEBUG_MODE=coverage ./vendor/bin/phpunit --configuration phpunit.xml --coverage-php coverage/php71.cov --coverage-html $CI_BUILD_REF_NAME/php71 --coverage-text --log-junit report.xml
    - vendor/bin/phpstan analyse src tests
  coverage: /\s+Lines:\s+(\d+\.\d+%)/
  artifacts:
    reports:
      junit: report.xml
    paths:
      - $CI_BUILD_REF_NAME
      - coverage/

test:php7.2:
  stage: test
  image: phpdocker/phpdocker:7.2
  tags:
    - dind
  before_script:
    - pecl install xdebug && docker-php-ext-enable xdebug
    - composer install --no-interaction
    - composer require --dev phpstan/phpstan
  script:
    #- phpcs --standard=PSR2 -nsp src tests
    - XDEBUG_MODE=coverage ./vendor/bin/phpunit --configuration phpunit.xml --coverage-php coverage/php72.cov --coverage-html $CI_BUILD_REF_NAME/php72 --coverage-text --log-junit report.xml
    - vendor/bin/phpstan analyse src tests
  coverage: /\s+Lines:\s+(\d+\.\d+%)/
  artifacts:
    reports:
      junit: report.xml
    paths:
      - $CI_BUILD_REF_NAME

test:php7.3:
  stage: test
  image: phpdocker/phpdocker:7.3
  tags:
    - dind
  before_script:
    - pecl install xdebug && docker-php-ext-enable xdebug
    - composer install --no-interaction
    - composer require --dev phpstan/phpstan
  script:
    #- phpcs --standard=PSR2 -nsp src tests
    - XDEBUG_MODE=coverage ./vendor/bin/phpunit --configuration phpunit.xml --coverage-php coverage/php73.cov --coverage-html $CI_BUILD_REF_NAME/php73 --coverage-text --log-junit report.xml
    - vendor/bin/phpstan analyse src tests
  coverage: /\s+Lines:\s+(\d+\.\d+%)/
  artifacts:
    reports:
      junit: report.xml
    paths:
      - $CI_BUILD_REF_NAME

test:php7.4:
  stage: test
  image: phpdocker/phpdocker:7.4
  tags:
    - dind
  before_script:
    - pecl install xdebug && docker-php-ext-enable xdebug
    - composer self-update
    - composer install --no-interaction
    - composer require --dev phpstan/phpstan
  script:
    #- phpcs --standard=PSR2 -nsp src tests
    - XDEBUG_MODE=coverage ./vendor/bin/phpunit --configuration phpunit.xml --coverage-php coverage/php74.cov --coverage-html $CI_BUILD_REF_NAME/php74 --coverage-text --log-junit report.xml
    - vendor/bin/phpstan analyse src tests
    - ls -lah pages
  coverage: /\s+Lines:\s+(\d+\.\d+%)/
  artifacts:
    reports:
      junit: report.xml
    paths:
      - $CI_BUILD_REF_NAME
      - coverage
      - tests/clover.xml

pages:
  cache:
    paths:
      - public
  before_script:
    - echo "skip before_script"
  stage: deploy
  image: busybox
  tags:
    - dind
  script:
    - echo "Copying public dic..."
    - rm -rf public && mv pages public
    - cp -R $CI_BUILD_REF_NAME public/$CI_BUILD_REF_NAME
    - cp public/index.html public/$CI_BUILD_REF_NAME/
    - echo $CI_PAGES_DOMAIN
    - echo $CI_PAGES_URL
  artifacts:
    paths:
      - public
  environment: 
    name: review/$CI_BUILD_REF_NAME 
    url: $CI_PAGES_URL/$CI_BUILD_REF_NAME/
  only:
    - master
