image:
  file: .gitpod.Dockerfile

ports:
  - port: 8001
    onOpen: open-browser

tasks:
  - before: sudo bash .gp/bash/init-ioncube.sh
  - init: bash .gitpod-init.sh
  - name: Apache
    command: >
        apachectl start;
        multitail /var/log/apache2/error.log -I /var/log/apache2/access.log